### ISSUE TITLE
While retranscoding the old thumbnail should get removed

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/transcoder#166]
During the retranscode, there could the the media files which were already transcoded. That means there will be a thumbnail as well for each file.

Now, for the better user experience, we should remove the previously generated thumbnail. 

![Media_Library_‹_thumbnail-demo_dev3_rt_gw_—_WordPress](https://user-images.githubusercontent.com/15173772/81559452-0920ef00-93ad-11ea-934d-14e8c39631b6.png)

**Comment by kjnanda** [comment]
NOTE: I have tested this with only VIP plugin. Please cross-check if this happens with non VIP code as well.

CC @dhaval-parekh

**Comment by dhaval-parekh** [comment]
@kjnanda I have added this feature. Please have a look at the below sites.

- https://dharmin.dev3.rt.gw/
- https://thumbnail-demo.dev3.rt.gw/
