### ISSUE TITLE
Error playing video during transcoding.

### ISSUE THREAD

**Issue by TremiDkhar** [rtCamp/transcoder#232]
After uploading the video to the activity, the video cannot be played instead it produces an error as shown in the screenshot.

![image](https://user-images.githubusercontent.com/14808994/111761295-c16ccd00-88c5-11eb-8c6b-9753c34ad3f1.png)

**Comment by pooja-muchandikar** [comment]
@tremidkhar 

The fix added is only working on Media opened in lightbox. But for media from activity page the message is not visible. 

## Snapshot of Media in lightbox

![image](https://user-images.githubusercontent.com/41000648/112416504-cf01d700-8d4b-11eb-971a-fe8906b2909d.png)

---

## Snapshot of activity page

![image](https://user-images.githubusercontent.com/41000648/112416348-86e2b480-8d4b-11eb-8446-c57e2f9e5911.png)

---

**Comment by tremidkhar** [comment]
@pooja-muchandikar According to my analysis, the error is produced by the rtMedia plugin, not by the transcoder anymore.
