### ISSUE TITLE
Transcoding Failing for 3gp video

### ISSUE THREAD

**Issue by aviral-mittal** [rtCamp/transcoder#264]
@Souptik2001 

As we discussed just now, on our internal development site, transcoding failed when we tried to transcode a 3gp video. 

Please check if the issue is reproducing on other sites and if something needs fixing.

**Comment by aviral-mittal** [comment]
@pavanpatil1 Instead of creating another issue, can you please add the details of that ticket where the video transcoding was not working?

**Comment by pavanpatil1** [comment]
Same as 3gp, the .mov file is not transcoding. After adding the.mov file the below message is displayed: 

`Unfortunately, Transcoder failed to transcode this file.
`

https://user-images.githubusercontent.com/44057535/223629989-564afddd-078a-49b7-90ff-26c5242cb379.mp4

Ref - https://rtmedia.io/ticket/2887990/

**Comment by aviral-mittal** [comment]
@sudhir-yadav Can you please take a look and fix this issue?

**Comment by sudhir-yadav** [comment]
@aviral-mittal  on it

**Comment by pavanpatil1** [comment]
<h3>Update: </h3>

I have checked the .mov file provided by the customer, With that file, the below message is visible. 

`This file is still in the queue. Please refresh after some time.`


Note: I have checked the status of the file in https://api.rtmedia.io/ there it shows the media is proceed successfully but on frontend the above message is displayed. 

@sudhir-yadav check the below .mov file and let me know if you need any other details. 



https://user-images.githubusercontent.com/44057535/223704251-20a66e1d-194c-49ae-b067-83b7a0feee60.mov

**Comment by pavanpatil1** [comment]
<h3>Update: </h3>

I have checked the .mov file provided on ticket, With that file, the below message is visible. 

`This file is still in the queue. Please refresh after some time.`


Note: I have checked the status of the file in server there it shows the media is proceed successfully but on frontend the above message is displayed. 

@sudhir-yadav check the below .mov file and let me know if you need any other details. 



https://user-images.githubusercontent.com/44057535/223704251-20a66e1d-194c-49ae-b067-83b7a0feee60.mov

**Comment by sudhir-yadav** [comment]
@pavanpatil1  @aviral-mittal   This has been fixed.

**Comment by pavanpatil1** [comment]
Verified the fix. It is working fine. Checked both the .mov and.3gp extension both are transcoding fine and on the server able to see the status of it. 

![image](https://user-images.githubusercontent.com/44057535/225541992-37d0a5f7-7f15-4c9f-b236-8251e4db1d49.png)


@sudhir-yadav is the fix from the plugin or server repo? . 


cc: @aviral-mittal @sudhir-yadav

**Comment by aviral-mittal** [comment]
Thanks @dhsathiya @nitun @dishitpala @sudhir-yadav for looking into this on priority. 

@pavanpatil1 The issue has been fixed on server side and no changes have been made to the plugin. We can inform the clients who were facing the issue now. 

Closing this issue.
