### ISSUE TITLE
Wrong file types under file browser while uploading media.

### ISSUE THREAD

**Issue by pranali333** [rtCamp/transcoder#31]
When we activate Transcoder plugin and we browse for the file while uploading media, the file browser shows all the files types ( including which are not allowed to upload via plugin).

For example:

Here is the screenshot of file browser without transcoder plugin:

![file-browser-without-transcoder](https://cloud.githubusercontent.com/assets/7771963/23546336/254ef48e-0025-11e7-9315-a4c0a2611248.png)

Here is the screenshot of file browser with transcoder plugin:

![file-browser-with-transcoder](https://cloud.githubusercontent.com/assets/7771963/23546354/3ade81a2-0025-11e7-8cc5-0d5156842669.png)

Please, look into it.

Thank you,
Pranali

**Comment by pranali333** [comment]
Fix: https://github.com/rtMediaWP/transcoder/pull/33/commits/600b2b6a64a9f5c9441c107fc05135efcd5c7c61

**Comment by BhargavBhandari90** [comment]
@pranali333 Not fixed.

**Comment by pranali333** [comment]
@sudhir-yadav looks like you are checking on this issue so assigned this to you.

Are you not seeing the other file types `PDF/TXT` while uploading?

**Comment by sudhir-yadav** [comment]
@pranali333  Ok got the issue, I am looking into it.

**Comment by kjnanda** [comment]
@sudhir-yadav The added fix works fine for the front end but in bbpress forum it still shows the format that is not supported by the transcoder plugin.

Please refer this visual - https://nimb.ws/hTdk3a

```
Test Url - https://transcoder.dev2.rt.gw/
Forum link - https://transcoder.dev2.rt.gw/groups/test/forum/
```

**Comment by kjnanda** [comment]
@sudhir-yadav Please ignore the above comment - https://github.com/rtMediaWP/transcoder/issues/31#issuecomment-482101979

The added fix works as expected.
